kafka_utils/kafka_cluster_manager/main.py

This allows to specify the group parser as: --group-parser my.module

Support local import for group-parser

---

docker/kafka_0.8.2/config.properties
docker/kafka_0.9.0/config.properties
tests/acceptance/environment.py
tests/acceptance/kafka_check.feature
tests/acceptance/steps/__init__.py
tests/acceptance/steps/common.py
tests/acceptance/steps/min_isr.py
tests/acceptance/steps/util.py

Add removing all topics from Kafka before each Scenario.
Put back kafka-check test with empty cluster.
Some minor fixes after that.

Fix acceptance tests

---

kafka_utils/util/config.py

HOME environment is not always set.

fix config when HOME is not in environment

---

kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
kafka_utils/kafka_cluster_manager/cluster_info/rg.py
kafka_utils/kafka_cluster_manager/cluster_info/util.py
tests/kafka_cluster_manager/cluster_topology_test.py
tests/kafka_cluster_manager/rg_test.py
tests/kafka_cluster_manager/util_test.py

Change separate_groups to extend underloaded with elements with optimal count.
Fix a bug in force_broker_decommission (missing break).
Add tests to cover both edge cases.

Fix two decommissioning bugs

---

README.md
docs/source/kafka_check.rst
kafka_utils/kafka_check/commands/under_replicated.py
kafka_utils/kafka_check/main.py
tests/kafka_check/test_under_replicated.py

It iterates across all brokers from the cluster and query them via jolokia port about under replicated partitions number. Returns OK if 0 of them, CRITICAL otherwise.

Add under_replicated sub-command for kafka-check

---

kafka_utils/kafka_check/commands/under_replicated.py
kafka_utils/kafka_check/main.py

It's just simple check, I decided not to add logger for that.

Add verbose option for kafka-check

---

docs/source/kafka_check.rst
kafka_utils/kafka_check/commands/min_isr.py
kafka_utils/kafka_check/commands/under_replicated.py
kafka_utils/kafka_check/main.py
tests/acceptance/min_isr.feature
tests/acceptance/steps/min_isr.py
tests/acceptance/steps/under_replicated.py
tests/acceptance/under_replicated.feature
tests/kafka_check/test_under_replicated.py

Add acceptance tests for under_replicated command
Rename min_isr tests

Use Kafka metadata request instead of Jolokia in under replicated

---

kafka_utils/kafka_cluster_manager/cluster_info/rg.py

Fix two log lines in kafka cluster manager.

Fix small typo in logging

---

kafka_utils/kafka_check/main.py

Disable for prevent this check to be timed out with sensu.

Disable logging

---

kafka_utils/__init__.py

Bump version for decommission bug due to empty replication-group found

---

README.md
kafka_utils/kafka_consumer_manager/commands/watermark_get.py
kafka_utils/kafka_consumer_manager/main.py
kafka_utils/util/monitoring.py
tests/acceptance/steps/util.py
tests/acceptance/steps/watermark_get.py
tests/acceptance/watermark_get.feature
tests/kafka_consumer_manager/test_watermark_get.py
tests/util/test_monitoring.py
tests/util/test_offsets.py

make test passes
Added documentation for using it

Create subcommand to get topic watermark

---

.travis.yml

see whether this fixes the build.

Add --force-yes

---

kafka_utils/kafka_consumer_manager/commands/offset_get.py
kafka_utils/kafka_consumer_manager/commands/offset_manager.py
tests/acceptance/offset_get.feature
tests/acceptance/steps/offset_get.py
tests/acceptance/steps/util.py

remove non-json part from --json output.
add itest for this change.

Improve consumer manager json ouput

---

CHANGELOG.rst
kafka_utils/__init__.py
kafka_utils/kafka_cluster_manager/cluster_info/rg.py
tests/kafka_cluster_manager/cluster_topology_test.py
tests/kafka_cluster_manager/rg_test.py

In the test case: Before the fix the net_imbal is 3, the original imbal is 5

Fix update of sibling-count bug

---

docs/source/kafka_consumer_manager.rst

correcting docs

---

kafka_utils/kafka_consumer_manager/commands/offset_get.py
tests/acceptance/steps/offset_get.py

E.g.: 
Cluster name: abc, consumer group: def
Topic Name: xyz
Partition ID: 0
High Watermark: 2488
Low Watermark: 2484
Current Offset: 125
Offset Distance: 2363 (Percentage behind: 0.95%)

Adding option to print offset-distance

---

.travis.yml

Should be mostly whitespace except for 'deploy' key.

Setup pypi autodeploy through travis

---

Makefile
docker/itest_0.10.1.1/Dockerfile
docker/itest_0.10.1.1/download-kafka.sh
docker/itest_0.10.1.1/run_tests.sh
docker/kafka_0.10.1.1/Dockerfile
docker/kafka_0.10.1.1/config.properties
docker/kafka_0.10.1.1/download-kafka.sh
tests/acceptance/copy_group.feature
tests/acceptance/list_groups.feature
tests/acceptance/list_topics.feature
tests/acceptance/offset_advance.feature
tests/acceptance/offset_get.feature
tests/acceptance/offset_rewind.feature
tests/acceptance/offset_save.feature
tests/acceptance/rename_group.feature
tox.ini

Add support for kafka 0.10.1.1 docker tests.
This refers internal ticket: KAFKA-4249

adding support for kafka 0.10.1.1

---

docs/source/kafka_cluster_manager.rst
kafka_utils/kafka_cluster_manager/cluster_info/broker.py
kafka_utils/kafka_cluster_manager/cluster_info/partition_count_balancer.py
kafka_utils/kafka_cluster_manager/cmds/revoke_leadership.py
kafka_utils/kafka_cluster_manager/main.py
tests/kafka_cluster_manager/partition_count_balancer_test.py

Command to revoke leadership for given set of brokers and transfer the leadership to other brokers in a balanced manner.

Revoke leadership of brokers

---

kafka_utils/util/zookeeper.py
tests/acceptance/change_topic_config.feature
tests/acceptance/steps/config_update.py
tests/acceptance/steps/util.py
tests/util/zookeeper_test.py
tox.ini

Refers internal ticket: KAFKA-5160
Currently this tool is broken, and this PR fixes this for both kafka 9 and kafka 10

Fix kafka topic config setter

---

kafka_utils/kafka_cluster_manager/cmds/command.py

See issue #119. The message could be improved.

Improve info message when a plan doesn't get executed

---

kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py

Fix kafka-cluster-manager argument

---

docs/source/kafka_rolling_restart.rst
kafka_utils/kafka_rolling_restart/main.py

added options to specify custom start and stop command

---

docs/source/kafka_consumer_manager.rst
kafka_utils/util/offsets.py
tests/util/test_offsets.py

Fix docs for offset_get command

---

kafka_utils/util/ssh.py

added openssh config to kafka utils

---

kafka_utils/kafka_rolling_restart/main.py

allowed for hostname to change its IP

---

kafka_utils/util/zookeeper.py
tests/util/zookeeper_test.py

Fetch creation time of topic and partition in the function "get_topics".
In order to do this, also changed the _fetch_partition_state  function to _fetch_partition_info, to return the creation time with the state information rather than only state information. Test added.

Fetch creation time of topic and partition.

---

docs/source/kafka_check.rst

Update documentation for kafka-check min_isr --default-min-isr 

---

kafka_utils/util/zookeeper.py
tests/util/zookeeper_test.py

Catch Exceptions for commands under empty cluster exception

Add NoNodeError to get_brokers & get_topics

---

kafka_utils/kafka_check/commands/command.py
tests/kafka_check/test_is_first_broker.py

- refactored is_first_broker method 
- added unit tests

kafka-check command checks for empty broker ids before running command

---

.gitignore
kafka_utils/kafka_rolling_restart/main.py
kafka_utils/util/ssh.py

Added a --ssh-password parameter to the kafka-rolling-restart command.

Add ssh password option to kafka-rolling-restart

---

kafka_utils/util/ssh.py

Make life 100% easier to debug socket error, and I fixed a logging bug on ex-line 125 for the logging...

fixed logging on SSH Socket Exceptions

---

requirements-dev.txt

Upgrade the setuptools version used in requirements-dev.txt to 40.0.0

KAFKA-13478: Bump setuptools version.

---

kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py

The best of the two will be picked.
When replacing a broker with a new one, it often happens that the new
broker is empty and can be picked as leader for all/most of the
partitions on the broker to be decommissioned.
This change will explore adding each broker to the replica set of
partitions as a follower, and as a leader.

Add brokers as follower and leader when decommissioning brokers.

---

kafka_utils/kafka_check/commands/min_isr.py
kafka_utils/kafka_check/commands/replication_factor.py
kafka_utils/kafka_check/main.py
tests/acceptance/replication_factor.feature
tests/acceptance/steps/replication_factor.py
tests/kafka_check/test_min_isr.py
tests/kafka_check/test_replication_factor.py

The command checks topics replication factor with min.isr settings and
alerts if replication_factor < min.isr + 1.
Add acceptance tests for replication_factor command

Implement kafka-check replication_factor command

---

docker/itest/Dockerfile
docker/kafka/Dockerfile
docker/zookeeper/Dockerfile
setup.py

Migrate to ubuntu 16.04 in acceptance tests
Update team name and email

Use openjdk instead of oracle-java8 in acceptance tests

---

kafka_utils/util/zookeeper.py

This speeds up the plan execution step as it will fetch the current plan only for the topics in proposed plan.

Speed up rebalance plan execution

---

.travis.yml
Makefile
docker/itest/Dockerfile
kafka_utils/kafka_consumer_manager/commands/offset_manager.py
kafka_utils/kafka_consumer_manager/util.py
setup.py
tox.ini
tox_acceptance.ini

[kafka-consumer-manager] Not showing error for successful commit

---

kafka_utils/util/metadata.py

In the case where topics are being deleted while the offline check is
running, there can be a race condition making the topic_partitions dict
inconsistent (slot not updated because some data in `topic_partitions`
is not part of `resp` as a topic was deleted in between).

Make kafka_check/offline resilient to topic deletion

---

kafka_utils/kafka_consumer_manager/util.py
tests/kafka_consumer_manager/test_utils.py

This should fix https://github.com/Yelp/kafka-utils/issues/214.

Support consumer offset message value schema v3

---

setup.py

set long description content type
