Yelp/kafka-utils

- CHANGELOG.rst
- kafka_utils/__init__.py
- kafka_utils/kafka_cluster_manager/cluster_info/rg.py
- tests/kafka_cluster_manager/cluster_topology_test.py
If there are no available brokers with destination broker for eligible partition (because all brokers already have a replica for the same) it should return None.
> Fix bug for No available brokers to move partition to

- kafka_utils/kafka_cluster_manager/main.py
By default fileConfig disables all loggers that are define before it is called. Most of our loggers are defined during application start and get disabled. This change prevent fileConfig from disabling them.
> Fix logging in kafka cluster manager

- kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
- tests/kafka_cluster_manager/cluster_topology_test.py
This bug makes impossible to decommission a broker that failed if there is no more metadata available to identify the origin replication group.
> Fix empty replication group error.

- .travis.yml
I don't think we need to pin a docker version. The build was failing because the docker version changed and the latest is not 1.11 but 1.12.
> Remove force-yes and remove pinned docker-engine

- kafka_utils/kafka_cluster_manager/cmds/rebalance.py
The replication group map can contain None keys when a broker is down. This should trigger a RebalanceError, but this logging line will fail first. This change will make sure that the logging line won't fail in presence of None values.
> Fix logging bug when rg is None

- kafka_utils/kafka_cluster_manager/cmds/command.py
- tests/kafka_cluster_manager/cmds/command_test.py
Some of the kafka-cluster-manager sub-commands (`rebalance`, `decommission`, `move-brokers`) fail with exit status `1` when there are no topics in the cluster. An empty cluster is not be an error so the exit status should be `0`. This is true for all sub-commands so we can make this change globally.
> Ensure kafka-cluster-manager commands exit cleanly on empty clusters

- kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
- kafka_utils/kafka_cluster_manager/cluster_info/error.py
- kafka_utils/kafka_cluster_manager/cluster_info/rg.py
- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/set_replication_factor.py
- kafka_utils/kafka_cluster_manager/main.py
- kafka_utils/util/validation.py
- kafka_utils/util/zookeeper.py
- tests/kafka_cluster_manager/cluster_topology_test.py
- tests/kafka_cluster_manager/cmds/command_test.py
- tests/kafka_cluster_manager/rg_test.py
- tests/util/validation_test.py
`usage: kafka-cluster-manager set_replication_factor [-h] --topic TOPIC replication_factor`
This command increases or decreases the replication factor of all partitions of a topic. It tries to do so in a way that spreads replicas across replication-groups and maintains the overall balance of the cluster.
> Add set_replication_factor sub-command to kafka-cluster-manager

- docs/source/kafka_consumer_manager.rst
group_id is no longer a valid option.
> Remove group_id from offset_restore documentation

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/decommission.py
- tests/kafka_cluster_manager/cmds/command_test.py
KAFKA-2392 Move pending assignment plan check to be a precondition of cluster manager operations so it is more obvious that it could become a blocker
> Move pending assignment plan check 

- tests/kafka_cluster_manager/cluster_topology_test.py
Original replica-imbalance is 1 before rebalancing partition-count. 
The replica-imbalance is guaranteed not to increase but it can reduce (which is good), that caused the flakiness in the result, wherein sometime net_imbal is either (0 or 1)
Since this test doesn't cater to testing replication-imbalance, will remove the check.
> Remove replica-imbalance flakiness

- kafka_utils/kafka_consumer_manager/commands/list_groups.py
- kafka_utils/kafka_consumer_manager/commands/list_topics.py
- kafka_utils/kafka_consumer_manager/commands/offset_get.py
- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- kafka_utils/kafka_consumer_manager/commands/offset_save.py
- kafka_utils/kafka_consumer_manager/commands/rename_group.py
- kafka_utils/kafka_consumer_manager/util.py
- kafka_utils/util/client.py
- requirements.txt
- setup.py
- tests/kafka_consumer_manager/test_utils.py
offset_get ignores --storage option when checking group existence
This will check if storage option is kafka, and in case it is, it will read list of topics form kafka and not from zookeeper. Default option is still zookeeper.
> offset_get ignores --storage option when checking group existence

- kafka_utils/kafka_cluster_manager/cmds/set_replication_factor.py
- tests/kafka_cluster_manager/cmds/set_replication_factor_test.py
The current value, `len(topic.partitions)`, is incorrect because `get_reduced_assignment` counts each replica added/removed as a partition movement. This makes the command fail for cases where more than one replica is added/removed at once.
Also, `max_leader_only_changes` should be `0` since there should be no leader only changes.
> Correct max_partition_movements for set_replication_factor

- tests/acceptance/steps/util.py
Many tests require the `__consumer_offsets` topic to be present, and each of them tries to create it and waits for 10 seconds. This change will make sure that the initialization will be skipped if the topic already exists, making acceptance tests faster.
The sleep time has been increased since I've seen (rare) cases in which 10 seconds weren't enough. The initialization function will now wait 20 seconds, but only on the first run.
> Do not initialize the kafka offset topic if not needed

- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- kafka_utils/kafka_consumer_manager/util.py
- tests/kafka_consumer_manager/test_utils.py
The kafka-consumer-manager `offset_get` command, when used with offset storage set to `kafka`, reads the entire `__consumer_offsets` topic to find out the list of topics associated with a given group.
Given that `__consumer_offsets` can be several GBs, this can take quite a long time.
With this change, `offset_get` consumes only from the partition that stores the information on the specified group (kafka code [here](https://github.com/apache/kafka/blob/d092673838173d9dedbf5acf3f4e2cd8c736294f/core/src/main/scala/kafka/coordinator/GroupMetadataManager.scala)). This change should give us a 50x speed improvement on average.
> Offset manager single partition

- kafka_utils/kafka_consumer_manager/commands/offset_advance.py
- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- tests/acceptance/steps/offset_advance.py
- tests/acceptance/steps/util.py
The `offset_advance` command is ignoring the `storage` parameter.
After this fix, the `offset_get` command cannot be used to create the `__consumer_offsets` topic anymore, so I had to call the `set_consumer_offsets` explicitly.
> Fix storage options

- kafka_utils/kafka_consumer_manager/util.py
- tests/kafka_consumer_manager/test_utils.py
Fixes #85 by autodetecting the number of partitions for the `__commit_offsets` topic.
> Autodetect partition number

- kafka_utils/kafka_consumer_manager/util.py
- tests/kafka_consumer_manager/test_utils.py
make test
Verified consistency of list_topics subcommand results for statmonster group.
> Fix flakiness in kafka_consumer_manager list_topics subcommand

- setup.py
Let's not pin it down to an exact version so it is compatible with post version from our kafka-python fork
> Update kafka-python requirement in kafka utils

- kafka_utils/kafka_consumer_manager/commands/offset_get.py
- tests/acceptance/offset_get.feature
- tests/kafka_consumer_manager/test_offset_get.py
Sorting the output of offset_get by total lag for each topic is useful in case a consumer is consuming from many topics and we want to find which one or how many of them are lagging behind by a considerable amount.
> Offset get sort output

- kafka_utils/kafka_check/commands/command.py
- kafka_utils/kafka_check/main.py
- kafka_utils/kafka_check/status_code.py
Use function prepare_terminate_message() to convert error messages to
dict for passing it into terminate() function.
> Fix terminate() for exceptional cases

- setup.py
Now that we have a new upstream version as 1.3.3, our builds are breaking. Lets set upper limit to 1.3.3 instead of 1.4.0
> set upper limit of kafka python to 1.3.3

- kafka_utils/kafka_consumer_manager/commands/list_groups.py
- kafka_utils/kafka_consumer_manager/util.py
- tests/kafka_consumer_manager/test_list_groups.py
- tests/kafka_consumer_manager/test_utils.py
- Fix a bug when the __consumer_offsets consumer would take very long to scan the entire topic
- Fix a bug when the __consumer_offsets consumer would interrupt scanning the topic because of a timeout
- Add logging
Scanning the entire log takes quite some time, about 3-5 minutes on average.
Fixes #106
> Refactor kafka group reader

- kafka_utils/kafka_check/commands/offline.py
It should simplify investigation of offline partitions for Kafka cluster.
> Add handy command line print for offline partitions check with -v option

- kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py
- tests/kafka_cluster_manager/genetic_balancer_test.py
This change will make genetic rebalancer complete the full exploration when performing a rebalance. Completing the full exploration is important to reach a score value that is above the threshold.
The plan is then reduced right before the assignment.
> Don't limit genetic algorithm plan exploration

- .travis.yml
The integration tests for 0.10.1.1 weren't actually being run on Travis. They pass though, so that's great!
> Run integration tests for Kafka 0.10.1.1 on Travis

- docker/itest_0.10.1.1/run_tests.sh
- docker/itest_0.8.2/run_tests.sh
- docker/itest_0.9.0/run_tests.sh
- requirements-dev.txt
- tox.ini
- tox_acceptance.ini
I had to split up the tox file to use two separate distdir.
distdir was causing issues when running acceptance locally so I added that to the list of directories to remove upon test termination.
> Split the tox file and fix the test cleanup to run acceptance locally

- kafka_utils/kafka_cluster_manager/cluster_info/display.py
- kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py
- kafka_utils/kafka_cluster_manager/cluster_info/stats.py
- tests/kafka_cluster_manager/genetic_balancer_test.py
- tests/kafka_cluster_manager/stats_test.py
Consider the partition count CV when computing the final score. This change introduces a new criteria when rebalancing.
If the cluster is already balanced by only broker weight, the movement of the smallest partitions (smaller impact on broker weight) is implicitly preferred to improve the partition count criteria.
In clusters with lots of empty partitions this change improves the overall utilization.
Internal ticket KAFKA-5777
> Add support for partition and leader count in generic balancer

- kafka_utils/kafka_cluster_manager/main.py
Instead of letting the default unhandled exception handler print the exception to stdout, unhandled exceptions will now be logged according to the logging configuration provided.
> Add unhandled exception logging to kafka-cluster-manager

- docker/itest_0.10.1.1/download-kafka.sh
- docker/itest_0.8.2/download-kafka.sh
- docker/itest_0.9.0/download-kafka.sh
- docker/kafka_0.10.1.1/download-kafka.sh
- docker/kafka_0.8.2/download-kafka.sh
- docker/kafka_0.9.0/download-kafka.sh
- kafka_utils/kafka_consumer_manager/commands/offset_get.py
- kafka_utils/kafka_consumer_manager/commands/rename_group.py
- kafka_utils/util/__init__.py
- tox.ini
This change will configure tox to remove the docker network after every acceptance test, cleaning up the environment.
> KAFKA-1497 - Remove docker network after acceptance tests

- kafka_utils/kafka_check/commands/replica_unavailability.py
- kafka_utils/util/metadata.py
- tests/util/metadata_test.py
This change checks the list of replicas from zookeeper, and compare it with partition-metadata when error 9 (REPLICA_NOT_AVAILABLE_ERROR) is encountered, to get the list of unavailable brokers.
> List unavailable brokers in case replicas are unavailable

- .gitignore
- kafka_utils/kafka_consumer_manager/commands/unsubscribe_topics.py
- tests/kafka_consumer_manager/test_unsubscribe_topics.py
The unsuscribe_topics command of kafka_consumer_manager is now able to
unsuscribe only a subset of topics among all the ones consumed by the
consumer group. The --topics is mutually exclusive with the --topic
option and consequently with --partitions.
This is my first PR for this project, so please let me know whether I have to call in more reviewers and/or how to test my change manually (for now I only relied on unit tests).
> Add --topics option to kafka_consumer_manager unsuscribe_topics cmd

- kafka_utils/util/zookeeper.py
- tests/util/zookeeper_test.py
If a legitimate topic name is missing in the `/config/topics` path, it should return a default/empty dict rather than raising an exception which should occur only if the topic is non-existent. The topic can be missing in the config path if it is created Kafka version prior to 0.8.1.
> Handle missing topics in `/config/topics` ZK path

- kafka_utils/kafka_corruption_check/main.py
- kafka_utils/kafka_rolling_restart/main.py
Added new optional argument `--broker-ids` to `kafka-rolling-restart` command:
`kafka-rolling-restart --cluster-type xxxx --broker-ids x y z`
Will only restart brokers x, y, z in the cluster.
The new option accepts a space separated list of integer broker ids and will only restart the brokers specified by `--broker-ids` if it is present.
Also corrected documentation for `get_broker_list` function.
> --broker-ids option for rolling restart command

- kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
- kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py
- tests/kafka_cluster_manager/genetic_balancer_test.py
- tests/util/zookeeper_test.py
(I'm currently only focusing on the decommissioning process. In order to keep the review process smooth, I'll start adding changes for rebalance and other commands once this PR is merged.)
Generating a `_State` is an intensive task. Instead of generating a new
`_State` after each new replica assignement, use the one that just got
applied.
 
Generating a full cluster assignment for a `_State` is an intensive
task. Instead, only generate an assignment containing incremental
changes incurred by the state changes.
 
Finding the index of an element in a tuple multiple times is an
intensive task. Instead, generate index reverse lookup maps once and use
it each time.
 
Make the decommission process repeatable by adding partitions in
lexicographic order. This makes the verification easier. :-)
* …
> Improve performance of broker decommission process

- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
We generate the list of groups in `list_groups` command by calling `kafka_group_reader.read_groups().keys()`; so if a group is not in this list, it doesn't exist.
`kafka_group_reader.read_group()` is just a wrapper around the `read_groups()` method that gets the specific `group_id` entry from all of the groups (i.e., `read_groups().get(group_id, [])`. So if there are no topics for the group (`group_topics == []`) the group does not exist
> Show error message for nonexistent group in offset_get

- requirements-dev.txt
- requirements.txt
- setup.py
- tox.ini
Remove the cryptography dependency.
This also fixes the problem where "make test" fails locally on yelp dev boxes.
> KAFKA-13478: Remove cryptography dependency.

- kafka_utils/kafka_consumer_manager/main.py
ran make test and tried out all the options on a command. seemed to work
> Add verbose logging options for kafka-consumer-manager

- CHANGELOG.rst
- kafka_utils/__init__.py
- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- kafka_utils/kafka_consumer_manager/commands/unsubscribe_topics.py
- tests/kafka_consumer_manager/test_offset_manager.py
- tests/kafka_consumer_manager/test_unsubscribe_topics.py
This fixes a bug where using unsubscribe_topics with the --topics flag
displayed all of the subscribed topics of the given consumer group as
subject to change when only the topics supplied with --topics should be
changed.
The bug was cosmetic only, so no actual functionality was changed.
> Fix bug in unsubscribe_topics with --topics flag

- .travis.yml
- Makefile
- tox.ini
This is based off of https://github.com/Yelp/paasta/commit/49c1cd0c9c8c641ad3332360ba3c09ad9d8cac4c
Basically, we won't have to do the export PIP_INDEX_URL=... internally anymore.
I tested this both internally and externally, and it seemed to work.
> Allow for yelp-only usage of internal pypi

- kafka_utils/kafka_consumer_manager/util.py
Applies the fix observed in https://github.com/dpkp/kafka-python/issues/1742 to fix integration tests
> Fetch metadata for KafkaGroupReader consumer before partitions_for_topic

- requirements.txt
The current version uses deprecated features of `collections` module. This change fixes those deprecation warnings.
(All test cases pass on my machine.)
> Bump version for `requests` module in requirements

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/decommission.py
- kafka_utils/kafka_cluster_manager/cmds/rebalance.py
- kafka_utils/kafka_cluster_manager/cmds/replace.py
- kafka_utils/kafka_cluster_manager/cmds/revoke_leadership.py
- kafka_utils/kafka_cluster_manager/cmds/set_replication_factor.py
- tests/kafka_cluster_manager/cmds/command_test.py
I still need to test this internally, but want to get the code checked out first.
This will allow users to limit the size of decommission movements not just by # of partitions, but also by data size. The goal is to give users more flexibility in how they want to do decommissions.
By default, there is no data size limit, which makes this backwards compatible.
> Add support for --max-movement-size argument in decommission

- kafka_utils/kafka_cluster_manager/cmds/command.py
- tests/kafka_cluster_manager/cmds/command_test.py
There's a bug in decommission if max_movement_size becomes 0 and there are only 0-sized partitions left. This will mean no progress will be made.
This also makes the script more efficient in adding as many 0-size partitions as possible (up to given leader/partition movement cap) when doing other decommissions.
> Fix bug if --max-movement-size=0

- kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py
- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/decommission.py
- tests/kafka_cluster_manager/cmds/command_test.py
Need to do some more manual testing still.
- I noticed decommission still uses the scoring in genetic balancer, which takes in `self.args.max_movement_size` (passed in from the cmd line). In the previous change to decommission where we added this argument, we set the default value to be `float('inf')`. The issue is that now this `float('inf')` will be used in genetic balancer for scoring even if the user did not pass in `--max-movement-size`. So we set the default value to be `None` in the parser (matching the rebalance command) and only set it to `float('inf')` when we reduce the overall assignment.
- I also noticed that passing in `--max-movement-size 0` will cause divide-by-zero error in genetic balancer, so I just coerced it to 1 to avoid the issue in the balancer. Same with …
> max movement size improvements

- setup.py
Included PyYAML here since we switched to 5.10 in requirements.txt and didn't notice anything odd.
> Relax requirements for pytz and pyyaml

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/decommission.py
We incorrectly passed down Nonetype value as argument instead of default argument, `float('inf')`.
This is because I incorrectly assumed passing in kwarg as `None` would result in default kwarg value downstream overwriting it.
> Fix bug with --max-movement-size == None

- kafka_utils/kafka_check/commands/min_isr.py
- kafka_utils/kafka_check/commands/offline.py
- kafka_utils/kafka_check/commands/replica_unavailability.py
- kafka_utils/kafka_check/commands/replication_factor.py
- kafka_utils/kafka_check/main.py
- kafka_utils/kafka_check/status_code.py
- tests/kafka_check/test_min_isr.py
- tests/kafka_check/test_offline.py
- tests/kafka_check/test_replica_unavailability.py
- tests/kafka_check/test_replication_factor.py
Add few more tests for formatting functions of subcommands of kafka-check
We need that param to be able to pass affected topics/partitions into sensu.
Bash `| head/tail` pipeline doesn't work properly because of unusual handling of SIGPIPE on python side. Also bash pipe hides exit code of the first command. Python solution seems more sustainable.
> Implement --head option for kafka-check command

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/decommission.py
- requirements.txt
- setup.py
Adds a new dependency humanfriendly that we can start using to display bytes and other numbers in human friendly values
Some sample output
```
WARNING:DecommissionCmd:Max partition movement size is only 13.0 bytes, but remaining partitions to move range from 0.0 bytes to 4.12 GB. The decommission may be slower than expected
INFO:DecommissionCmd:Auto-max-movement-size: using 4.12 GB (4120645437.0) as max-movement-size.
ERROR:DecommissionCmd:Max partition movement size is only 1.0 byte, but remaining partitions to move range from 0.0 bytes to 4.12 GB. The decommission will not make progress
```
Wasn't able to test the case in `command.py` but it should work the same.
> Human friendly output for bytes in decommission

- kafka_utils/kafka_manual_throttle/__init__.py
- kafka_utils/kafka_manual_throttle/main.py
- kafka_utils/util/zookeeper.py
- scripts/kafka-manual-throttle
- tests/kafka_manual_throttle/test_main.py
- tests/util/zookeeper_test.py
NOTE: It may be easier for reviewers to have a look at each commit separately 🙂
-----
Add ZK.set_broker_config and ZK.get_broker_config
Getting/Setting broker configuration is neened to set replication throttles per broker.
Broker configurations can be changed the same way as topic
configurations, this commit refactors {set,get}_topic_config into
{set,get}_entity_config and use these to interact with broker and topic
configurations.
-----
Add kafka-manual-throttle command
This command allows to manually set or clear replication throttle values
for brokers in a cluster.
```
kafka-manual-throttle -t <type> -c <name> --leader 134217728 --follower 268435456
kafka-manual-throttle -t <type> -c <name> --clear
```
> Add kafka-manual-throttle command

- kafka_utils/kafka_cluster_manager/cmds/command.py
- tests/kafka_cluster_manager/cmds/command_test.py
The original code had a bug that was not possible to observe until the addition of the `--max-movement-size` parameter.
The bug is a simple one, basically just removing an element from a list while iterating through it. It will cause the loop to terminate early, e.g.
```python
things = [0, 1]
for thing in things:
print(thing)
things.remove(thing)
```
The above will only print out `0`, skipping `1`, as the loop terminates early.
We did observe the potential issue, but since we did not experience any actual issues, we did not change it. The reason we did not observe any actual issues before was due to the outer while loop in our code, which will continually loop through all actions (as long as we are guaranteed to find *some* action). Using the example above again,
```python
things = [0, 1] …
```
> Fix iteration bug in --max-movement-size extract actions

- kafka_utils/kafka_manual_throttle/main.py
- tests/kafka_manual_throttle/test_main.py
Instead of writing configuration in the `config` dict in Zookeeper,
kafka-manual-throttle was writing updates at the config toplevel. This
meant that Kafka was ignoring them.
Before:
{'config': {}, 'leader.replication.throttled.rate': XXXX}
After:
{'config': {'leader.replication.throttled.rate': XXXX}}
> Fix configuration writing in kafka-manual-throttle

- kafka_utils/kafka_consumer_manager/commands/offsets_for_timestamp.py
Print a warning message if the argument to the offsets_for_timestamp flag is not in milliseconds.
> Add warning if timestamp argument in offsets_for_timestamp is in seconds

- docker/itest/Dockerfile
The itest failure is due to a chain of dependencies that end up trying to
install more_itertools without specifying a version. `more_itertools`
dropped support for py27 with version 6.0.0, which causes failures when
trying to import it in a py27 environment with the same error as here:
https://github.com/pytest-dev/pytest/issues/4770
Why did it start failing this week? It looks like our internal pypi:
https://pypi.yelpcorp.com/simple/more-itertools/ has only had up to
version 4.2.0 recently, and @drmorr uploaded a wheel for v7.2.0
yesterday, which the py27 acceptance test is trying to install. It looks
like the old version of pip we’re using, as described in that github issue,
is trying to install the latest version of more-itertools, despite itest
being marked as only for py3, and …
> Fix itest on py27

- setup.py
This pinned version is too strict and it is causing dependency conflicts in some places.
Relaxing the requirement in setup.py looks like it should be safe.
> KAFKA-23818_relax_pytz_version

- kafka_utils/kafka_rolling_restart/main.py
- tests/kafka_rolling_restart/test_main.py
As suggested by #150, this PR adds an `--active-controller-for-last` parameter to the `kafka-rolling-restart` command.
By default, we keep the standard order (e.g. by broker id). If the flag is passed, the rolling restart will end by the current active controller.
> End the rolling restart by the active controller

- docs/source/kafka_rolling_restart.rst
- kafka_utils/kafka_rolling_restart/main.py
- tests/kafka_rolling_restart/test_main.py
Hey,
We use user & password in order to authenticate to Jolokia in our organization.
I added the ability to provide it by passing 2 more arguments - `--jolokia-password` and `--jolokia-user`.
In case of bad authentication credentials (401), the user will face `Jolokia Authentication Failed. Exiting.` error.
I updated the `docs/source/kafka_rolling_restart.rst` doc as well.
Thanks :upside_down_face:
> Adding Jolokia authentication support

- .pre-commit-config.yaml
- docker/itest/Dockerfile
- kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
- kafka_utils/kafka_cluster_manager/cluster_info/partition.py
- kafka_utils/kafka_cluster_manager/cmds/replace.py
- kafka_utils/util/validation.py
- tests/kafka_cluster_manager/cmds/replace_broker_test.py
This adds support for removing brokers from replica assignment. We specify a replica removal by having a source-broker with no dest-broker. Replica addition could also be added in a similar way, but I'm gonna leave that for the next PR.
Before it was not possible because the script would do two steps of verification for replacement:
1. Check that the overall replication factor of the topic partitions has not changed. This check can now be skipped with the `--rf-changes` flag
2. Check that the replication factor of topic partitions within the same topic is the same. This check can now be skipped with the `--rf-mismatch` flag.
We also introduce a `--topic-partition-filter` flag, that is a path to some output from `kafka-check`, so that you can focus on fixing offline or specific partitions …
> Add support for removing brokers in replace

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/set_replication_factor.py
- kafka_utils/util/zookeeper.py
- tests/kafka_cluster_manager/cmds/set_replication_factor_test.py
Some manual testing:
Suppose we have a topic with mismatched topic RF like so:
```
baisang@noneofyourbusiness ~/kafka-utils> kafka-info -t test topic test_topic
<...>
Partitions details:
Partition 0: Total size 0.0B
Leader <redacted>: Start offset 4, End offset 4, Size 0.0B
Follower <redacted>: Insync True, End offset 4, Size 0.0B
Partition 1: Total size 0.0B
Leader <redacted>: Start offset 0, End offset 0, Size 0.0B
Topic specific configuration:
None
```
Old set_replication_factor can't handle this situation properly:
```
baisang@noneofyourbusiness ~/kafka-utils> kafka-cluster-manager -t test set_replication_factor --topic test_topic 2
INFO:kazoo.client:Connecting to my_zk:2181
INFO:kazoo.client:Zookeeper connection established, state: CONNECTED
INFO:kafka-zookeeper-manager:Fetching …
```
> set_replication_factor command to handle mismatched replication factor partitions

- kafka_utils/kafka_cluster_manager/cmds/command.py
- kafka_utils/kafka_cluster_manager/cmds/preferred_replica_election.py
- kafka_utils/kafka_cluster_manager/cmds/replace.py
- kafka_utils/kafka_cluster_manager/main.py
This command will allow us to easily generate files for `kafka-preferred-replica-election` based on the output of `kafka-check`
> Add preferred replica election command to generate json files

- kafka_utils/kafka_consumer_manager/commands/copy_group.py
- kafka_utils/kafka_consumer_manager/commands/delete_group.py
- kafka_utils/kafka_consumer_manager/commands/list_groups.py
- kafka_utils/kafka_consumer_manager/commands/list_topics.py
- kafka_utils/kafka_consumer_manager/commands/offset_advance.py
- kafka_utils/kafka_consumer_manager/commands/offset_get.py
- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- kafka_utils/kafka_consumer_manager/commands/offset_rewind.py
- kafka_utils/kafka_consumer_manager/commands/offset_save.py
- kafka_utils/kafka_consumer_manager/commands/rename_group.py
- kafka_utils/kafka_consumer_manager/commands/unsubscribe_topics.py
- kafka_utils/kafka_consumer_manager/main.py
- kafka_utils/kafka_consumer_manager/util.py
- tests/kafka_consumer_manager/test_list_groups.py
- tests/kafka_consumer_manager/test_utils.py
Reading the __consumer_offsets topic at every run is slow and can add
unwanted load on a Kafka cluster. The AdminClient allows to get the list
of consumer groups and the list of topics from a group id in constance
time.
This is currently a feature flag to keep backwards compatibility, but
will later be enabled by default.
--use-admin-client
> Allow using Kafka AdminClient for kafka-consumer-manager commands

- kafka_utils/util/zookeeper.py
- tests/util/zookeeper_test.py
The goal of this PR is to be able to perform rolling restart in a Kafka Cluster using SSL or SASL
For plaintext broker when you get metadata from Zookeeper, the result is like that (this result is used to get broker's hostname):
```
{
"jmx_port":-1,
"timestamp":"1312312312",
"endpoints":[],
"host":"broker-hostname:9092",
"version":2,
"port":-1
}
````
for broker using SSL is like that:
```
{
"listener_security_protocol_map":{
"SSL":"SSL"
},
"endpoints":[
"SSL://broker-hostname:9093"
],
"jmx_port":-1,
"host":null,
"timestamp":"1584750310126",
"port":-1,
"version":4
}
```
for broker using SSL with internal and external mapping is like that:
```
{
"listener_security_protocol_map":{
"SSL":"SSL"
},
"endpoints":[
"INTERNAL://broker-hostname:9093",
"EXTERNAL://broker-hostname:9093"
], …
```
> Allow kafka-rolling-restart script to be executed in clusters with SSL our SASL enabled

- kafka_utils/util/utils.py
- tests/util/util_test.py
When using dynamic import to find a child class of `base_class`, if two
classes match the criteria (e.g: class A, class B(A), class C(B)),
dynamic_import would return B instead of C as it stops at the first
class found in the package that is a subclass of A.
This commit changes the behaviour to return the child-most class.
> Allow dynamic import to find the child-most class

- kafka_utils/kafka_cluster_manager/cmds/replace.py
- kafka_utils/kafka_corruption_check/main.py
- kafka_utils/util/validation.py
- requirements-dev.txt
- tests/acceptance/steps/min_isr.py
This will allow us to (actually) ignore errors of the form `Mismatch in replication-factor of partitions`. This is particularly useful when issuing commands to recover from incidents related to https://issues.apache.org/jira/browse/KAFKA-8733.
- Fix missing rf_mismatch arg in process_assignment
- Fix version conflict in requirements-dev
- Address various `flake8` issues
`make test` passes
> Fix missing rf_mismatch arg in process_assignment call

- README.md
- docs/source/config.rst
- kafka_utils/main.py
- kafka_utils/util/config.py
- tests/util/config_test.py
This changes the default directory used to read kafka discovery config files from `/etc/kafka_discovery` to `/nail/srv/configs/kafka_discovery_configs`. The actual format of the files does not change.
This will be released with a major version bump.
`make test` passes
> Change read directory of kafka_discovery files

- requirements-dev.txt
The current version of `cryptography` being pulled in the Jenkins build is `3.2`, which uses `setuptools v49.2.1`, which is not compatible with `py27`. Pinning `cryptography` to `3.0` prevents this from happening and this should get the Jenkins build to succeed.
`make test` now passes on a Jenkins host
> Pin cryptography version to 3.0

- README.md
- docs/source/config.rst
- kafka_utils/main.py
- kafka_utils/util/config.py
This is a slight change to https://github.com/Yelp/kafka-utils/pull/262 and we now only use the srv-configs directory if it exists on the host, otherwise we continue using the `/etc/kafka_discovery` directory for cluster discovery configuration files.
I will release this with a patch version bump.
> Use srv-configs for discovery only if it exists

- CHANGELOG.rst
- README.md
- docs/source/config.rst
- kafka_utils/main.py
- kafka_utils/util/config.py
- tests/util/config_test.py
This reverts the changes made in https://github.com/Yelp/kafka-utils/pull/265 and https://github.com/Yelp/kafka-utils/pull/262 since we now use a cron job to rsync files from the srv-configs directory.
`make test` passes
KAFKA-30532
minor version release (`v3.9.0`)
> Change the default Kafka discovery config directory back to /etc/kafka_discovery

- docs/source/kafka_check.rst
GitHub and https://kafka-utils.readthedocs.io/en/latest/kafka_check.html doesn't render the bullet points unless there's a newline before the start of the unordered list.
> Fix bullet point rendering on kafka_check.rst

- .github/workflows/kafka-utils-ci.yml
- docker/itest/Dockerfile
- docker/kafka/Dockerfile
- docker/zookeeper/Dockerfile
The only problems happened in our acceptance test suite, where we run everything from Docker containers. The main issue happened with how we were setting up our testing suite's virtual environment (in `docker/test/Dockerfile`) but I also took this chance to migrate to Ubuntu Bionic (18.04) and clean up some other sub-optimal things in our Dockerfiles.
Note that the GH action change is meant to reduce duplicate test runs when creating/updating a CR (see #270) and also ensure that all 3 test suites can run independently - so you still get test results for all 3 even if one fails.
This doesn't change the actual package we distribute, just how we test it.
> Fix gh acceptance build

- setup.py
- tox_acceptance.ini
Paramiko needs a lower version (https://github.com/Yelp/kafka-utils/issues/146) and we can also allow newer versions of Paramiko.
`make test` passes (with newer paramiko version)
I'll have to fix the Pypi.org release mechanism (https://github.com/Yelp/kafka-utils/issues/258) but I plan to do a patch release for this particular change.
> Increase upper pin and introduce lower pin on paramiko

- kafka_utils/kafka_consumer_manager/commands/offset_advance.py
If an `UnknownMemberIdError` is encountered while using `kafka-consumer-manager offset_advance`, users will see an error of the following form:
```
kafka.errors.UnknownMemberIdError: [Error 25] UnknownMemberIdError: OffsetCommitResponsePayload(topic='some_kafka_topic', partition=0, error=25)
```
This can be a bit opaque for users who are not familiar with the internals of Kafka.
We give users a more practical error message which instructs them to stop their consumer prior to attempting to advance offsets.
tests pass
`patch` release
> Add more descriptive error message when encountering UnknownMemberIdError while advancing offsets 

- requirements-dev.txt
Changes:
- Updated `ipdb` and `ipython` as they failed to install because of incompatibility issues with `setuptools==58.3.0`
- Pinned PyYAML in `requirements-dev.txt` as `PyYAML==6.0` is not compatible with `pre-commit==0.8.0` and `docker-compose==1.7.0`
> Fix build failing because of dependencies conflict

- .pre-commit-config.yaml
- requirements-dev.txt
Changes in requirements-dev:
- Removed `ipdb`, `ipython` dependencies.
- Removed `PyYAML` (it will still get installed by pre-commit(`PyYAML==6.0`), then overwritten when tox installs docker-compose (`PyYAML==3.13`).
- Updated `pre-commit` version to 1.14.4 to make it compatible with`PyYAML==6.0`.
> Fix internal build failing

- kafka_utils/kafka_cluster_manager/cmds/decommission.py
- tests/kafka_cluster_manager/decommission_test.py
If a broker is being decommissioned and it's already empty, we don't have any need to move other topics. Thus, `partitions_to_move` is an empty set.
Currently, the code will crash with an error:
```
[2021-11-09 15:36:05,992] [CRITICAL:main] Uncaught exception:
Traceback (most recent call last):
...
File "<>/site-packages/kafka_utils/kafka_cluster_manager/cmds/decommission.py", line 112, in run_command
for partition in partitions_to_move
ValueError: max() arg is an empty sequence
```
I added a unit test to reproduce this issue (it failed without these changes), and it passes now.
My understanding is that if the `partitions_to_move` is empty, then `self.args.max_movement_size ` being 1 doesn't have any impact.
Patch version release
> When a decommission node is empty, don't crash on max/min functions

- kafka_utils/kafka_check/commands/command.py
- kafka_utils/kafka_check/commands/min_isr.py
- kafka_utils/kafka_check/commands/offline.py
- kafka_utils/kafka_check/commands/replica_unavailability.py
- kafka_utils/kafka_check/commands/replication_factor.py
- kafka_utils/kafka_check/main.py
- kafka_utils/kafka_check/metadata_file.py
- kafka_utils/kafka_check/status_code.py
- kafka_utils/kafka_consumer_manager/commands/offset_set.py
- kafka_utils/kafka_consumer_manager/commands/offset_set_timestamp.py
- kafka_utils/util/client.py
- mypy.ini
- requirements-dev.txt
- requirements.txt
- setup.py
- tox.ini
This annotates the `kafka_utils.kafka_check` module. It doesn't have any real effect right now, but this repo is large so annotating in chunks makes sense.
I also migrated from retrying to tenacity, since retrying is a dead package and tenacity has type annotations.
> Add type annotations part 1

- kafka_utils/kafka_cluster_manager/cluster_info/broker.py
- kafka_utils/kafka_cluster_manager/cluster_info/cluster_balancer.py
- kafka_utils/kafka_cluster_manager/cluster_info/cluster_topology.py
- kafka_utils/kafka_cluster_manager/cluster_info/display.py
- kafka_utils/kafka_cluster_manager/cluster_info/genetic_balancer.py
- kafka_utils/kafka_cluster_manager/cluster_info/partition.py
- kafka_utils/kafka_cluster_manager/cluster_info/partition_count_balancer.py
- kafka_utils/kafka_cluster_manager/cluster_info/partition_measurer.py
- kafka_utils/kafka_cluster_manager/cluster_info/replication_group_parser.py
- kafka_utils/kafka_cluster_manager/cluster_info/rg.py
- kafka_utils/kafka_cluster_manager/cluster_info/stats.py
- kafka_utils/kafka_cluster_manager/cluster_info/topic.py
- kafka_utils/kafka_cluster_manager/cluster_info/util.py
- tests/kafka_cluster_manager/cmds/command_test.py
A few notable things here:
- ClusterTopology now requires the `extract_group` argument. This is because it was effectively required by the fact that it's called without checking for `None`. And all non-test usages set it.
- GeneticBalancer.rebalance had a logic error where it tries to iterate over a dict. This works but just iterates over the keys of the dict, not the items. I fixed this by calling `.items()` on the dict and iterating over that. This implies that this code is dead though, since it almost certainly crashed and definitely didn't work.
> add type annotations to kafka_utils.kafka_cluster_manager.cluster_info.broker

- kafka_utils/kafka_check/commands/command.py
- kafka_utils/kafka_check/commands/offline.py
- kafka_utils/kafka_check/commands/replica_unavailability.py
- kafka_utils/kafka_check/commands/replication_factor.py
- kafka_utils/kafka_check/main.py
- kafka_utils/kafka_consumer_manager/commands/copy_group.py
- kafka_utils/kafka_consumer_manager/commands/delete_group.py
- kafka_utils/kafka_consumer_manager/commands/list_groups.py
- kafka_utils/kafka_consumer_manager/commands/list_topics.py
- kafka_utils/kafka_consumer_manager/commands/offset_advance.py
- kafka_utils/kafka_consumer_manager/commands/offset_get.py
- kafka_utils/kafka_consumer_manager/commands/offset_manager.py
- kafka_utils/kafka_consumer_manager/util.py
- kafka_utils/util/__init__.py
- kafka_utils/util/client.py
- kafka_utils/util/config.py
- kafka_utils/util/error.py
- kafka_utils/util/metadata.py
- kafka_utils/util/monitoring.py
- kafka_utils/util/offsets.py
- kafka_utils/util/protocol.py
- kafka_utils/util/serialization.py
- kafka_utils/util/ssh.py
- kafka_utils/util/utils.py
- kafka_utils/util/validation.py
- kafka_utils/util/zookeeper.py
- mypy.ini
- setup.py
- tests/util/zookeeper_test.py
This adds type annotations to all of `kafka_utils.util` and some of `kafka_utils.kafka_consumer_manager.commands`. I started on the latter module before we realized that `kafka_utils.util` was the only module that was meaningfully used.
There's probably more room for better TypedDicts in here (especially in `kafka_utils/util/zookeeper.py`), but I think this is good enough for now.
> Add type annotations part 3
